### ISSUE TITLE
Create migration and model for share game modules

### ISSUE THREAD

**Issue by Augusztinovics** [Augusztinovics/rpg_game_app#12]
Similar as game module and game module data. Need to add column for shared in game module as well

**Comment by daniel-werner** [comment]
public_game_modules: nem kell: gm_id, game_module_state, game_active, game_chat
game_modules: kell: shared true/false
public_game_module_data: nem kell: game_module_data_order

**Comment by daniel-werner** [comment]
Ready for the next challenge :)
