### ISSUE TITLE
Character Sheet for Magus

### ISSUE THREAD

**Issue by Augusztinovics** [Augusztinovics/rpg_game_app#2]
Dod: have characterSheet.html file
How: create characterSheet.html file what is similar to attached pictures.
  -No styling jet, just markup

![sheet1](https://user-images.githubusercontent.com/87669312/192446087-8f011796-69d5-4b4c-885c-c85a7d2ec5dc.jpg)
![sheet2](https://user-images.githubusercontent.com/87669312/192446116-194d7e16-1571-4580-a10d-2956758ddfe0.jpg)

**Comment by ifbian** [comment]
working on it.
