### ISSUE TITLE
Style Character Sheet

### ISSUE THREAD

**Issue by Augusztinovics** [Augusztinovics/rpg_game_app#3]
Dod: characterSheet.html looks similar as in picture ( not need exact )
How: Use inline style attribute in html elements and style. Not wory exact font, dont include font family

![sheet1](https://user-images.githubusercontent.com/87669312/192446969-8a1c235f-1c30-484f-bb6e-9860f48064a9.jpg)
![sheet2](https://user-images.githubusercontent.com/87669312/192446988-0d44a4e0-d7ac-4c06-aee0-3ab5d115dd23.jpg)

**Comment by pkaustubh401** [comment]
Hey @Augusztinovics , I am really good At CSS and would like to contribute to this issue. We can discuss it and I will complete it for you

**Comment by Augusztinovics** [comment]
That ok, but first need someone to finish the HTML markup.

**Comment by pkaustubh401** [comment]
Okay , Where can I find the HTML file to be updated, Or do I have to create a new HTML file and design it like the image mentioned above

**Comment by Augusztinovics** [comment]
need to make. Ticket #2  is for that purpose. Just put in resources/views folder
